<?php
/**
 * Created by PhpStorm.
 * User: Justin
 * Date: 2017/7/18
 * Time: 16:02
 */
namespace books\services\book;

use revolver\components\service\SearchService;
use books\models\db\BookModel;

class BookSearch extends SearchService
{
    public static $defaultModelName = 'books\models\db\BookModel';

    public function getList()
    {
        // 设置枚举
//        $this->setEnums([
//            'user'=>[
//                'type'=>[
//                    1=>'admin',
//                    2=>'user'
//                ]
//            ]
//        ]);

        // 设置搜索配置
        $this->setSearchOps([
            'from' => BookModel::tableName().' as b',
            'select'=>['b.*', 'u.name user_name', 'u.phone'],
            'join'=>[
                ['left join', 'user u', 'u.id = b.user_id']
            ],
            'andFilterWhere' => [
                ['b.status'=>$this->form->status],
                ['u.phone'=>$this->form->phone],
                ['like', 'b.key_word', $this->form->key_word]
            ],
            'orderBy' => ['b.id' => SORT_DESC],
            'groupBy' => ['b.id']
        ]);

        return parent::getList(); // TODO: Change the autogenerated stub
    }

//    public function getDetail()
//    {
//        $this->setSearchOps([
//            'from' => BookModel::tableName().' as b',
//            'andWhere' => [['b.id'=>$this->form->id]],
//            'select'=>['b.*', 'u.name user_name', 'u.phone'],
//            'join'=>[
//                ['left join', 'user u', 'u.id = b.user_id']
//            ]
//        ]);
//
//        return parent::getDetail(); // TODO: Change the autogenerated stub
//    }

}