<?php
/**
 * Created by PhpStorm.
 * User: Justin
 * Date: 2017/7/18
 * Time: 16:02
 */
namespace books\services\book;

use app\components\service\EditService;

class BookEdit extends EditService
{

    public function add()
    {

        return parent::add(); // TODO: Change the autogenerated stub
    }
}