<?php
/**
 * Created by PhpStorm.
 * User: Justin
 * Date: 2017/7/18
 * Time: 16:02
 */
namespace books\services\book;

use revolver\components\service\EditService;
use books\models\db\HistoryModel;
use yii\db\Exception;

class BookEdit extends EditService
{
    public static $defaultModelName = 'books\models\db\BookModel';

    public function create()
    {
        self::beginTransaction();

        try{
            $id = parent::create(); // TODO: Change the autogenerated stub

            $data = [
                'book_id' => $id,
                'do_type' => 5,
                'do_time' => date('Y-m-d H:i:s')
            ];

            $HM = new HistoryModel();
            $HM->setAttributes($data);
            $HM->save();
            self::commitTransaction();
        }catch(Exception $e){
//            $T->rollBack();
            self::rollBackTransaction();
        }

        return $id;
    }


    public function update()
    {
        self::beginTransaction();

        try{
            parent::update(); // TODO: Change the autogenerated stub

            $data = [
                'book_id'=>$this->form->id,
                'do_type' => 6,
                'do_time' => date('Y-m-d H:i:s')
            ];

            $HM = new HistoryModel();
            $HM->setAttributes($data);
            $HM->save();
            self::commitTransaction();
            return true;
        }catch (Exception $e){
            self::rollBackTransaction();
            return false;
        }

    }
}