<?php
/**
 * Created by PhpStorm.
 * User: Justin
 * Date: 2017/7/18
 * Time: 16:02
 */
namespace books\services\book;

use app\components\service\SearchService;
use books\models\db\BookModel;

class BookSearch extends SearchService
{
    protected $defaultModel = 'books\models\db\BookModel';

    public function getList()
    {
        $this->setSearchOps([
            'from' => BookModel::tableName().' as b',
            'select'=>['b.*', 'u.name user_name', 'u.phone'],
            'join'=>[
                ['left join', 'user u', 'u.id = b.user_id']
            ],
            'andFilerWhere' => [
                ['b.status'=>$this->form->status],
                ['u.phone'=>$this->form->phone],
                ['b.key_word'=>$this->form->key_word],
            ]
        ]);

        p($this->getSearchOps());exit;
        return parent::getList(); // TODO: Change the autogenerated stub
    }

}