<?php
/**
 * Created by PhpStorm.
 * User: Justin
 * Date: 2017/7/18
 * Time: 16:02
 */
namespace books\services\book;

use app\components\service\EditService;
use app\components\service\ServiceException;
use books\models\db\HistoryModel;
use yii\db\Transaction;

class BookEdit extends EditService
{
    public static $defaultModelName = 'books\models\db\BookModel';

    public function create()
    {
        $M = $this->getDefauleModel();
        $T = new Transaction(['db'=>$M::getDb()]);
        $T->begin();

        try{
            $id = parent::create(); // TODO: Change the autogenerated stub

            $data = [
                'book_id' => $id,
                'do_type' => 5,
                'do_time' => date('Y-m-d H:i:s')
            ];

            $HM = new HistoryModel();
            $HM->setAttributes($data);
            $HM->save();
            $T->commit();
        }catch(Exception $e){
            $T->rollBack();
        }

        return $id;
    }
}