<?php

namespace books\controllers;

use app\components\rest\ResponseFormat;
use books\services\book\BookEdit;
use books\services\book\BookSearch;
use Yii;
use app\components\rest\Controller;


/**
 * Book
 */
class BookController extends Controller
{

    public function init()
    {
        $this->checkForm = 'books\models\form\BookForm';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function verbs()
    {
        return [
            'list' => ['post'],
            'detail' => ['post'],
            'create' => ['post'],
            'update' => ['post']
        ];
    }

    public function actionList()
    {
        $obj = BookSearch::getInstance();
        $result = $obj->checkform($this->checkForm, 'list')->getList();
        return new ResponseFormat(['data' => $result, 'enum' => $obj::getEnums()]);
    }


    public function actionDetail()
    {
        $obj = BookSearch::getInstance();
        $result = $obj->checkform($this->checkForm, 'detail')->getDetail();
        return new ResponseFormat(['data' => $result, 'enum' => $obj::getEnums()]);
    }


    public function actionCreate()
    {
        $result = BookEdit::getInstance()->checkform($this->checkForm, 'create')->create();
        return new ResponseFormat(['data'=>$result]);
    }

    public function actionUpdate()
    {
        $result = BookEdit::getInstance()->checkform($this->checkForm, 'update')->update();
        return new ResponseFormat(['data'=>$result]);
    }




}
